prometheus:
  url: http://monitoring-kube-prometheus-prometheus.monitoring.svc
  port: 9090

rules:
  default: true
  custom:
    - seriesQuery: 'job_processor_threads_used{namespace!="",pod!=""}'
      resources:
        overrides:
          namespace: {resource: "namespace"}
          pod: {resource: "pod"}
      name:
        matches: "job_processor_threads_used"
        as: "threads_busy"
      metricsQuery: 'sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)'