server:
  port: 9090

processor:
  max-threads: 4
  metrics-names:
    used-threads:
      name: job_processor_threads_used
      descr: how many thread are currently in use processing data

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus